#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xb95b937f, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x6d662533, __VMLINUX_SYMBOL_STR(_find_first_bit_le) },
	{ 0xc807fb01, __VMLINUX_SYMBOL_STR(blk_queue_merge_bvec) },
	{ 0x55b2bdeb, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xd01d57ff, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x4d7272e4, __VMLINUX_SYMBOL_STR(migrate_enable) },
	{ 0xff178f6, __VMLINUX_SYMBOL_STR(__aeabi_idivmod) },
	{ 0xa6940f91, __VMLINUX_SYMBOL_STR(async_raid6_datap_recov) },
	{ 0x3615401d, __VMLINUX_SYMBOL_STR(blk_queue_io_opt) },
	{ 0x506447e4, __VMLINUX_SYMBOL_STR(mddev_congested) },
	{ 0xb1540781, __VMLINUX_SYMBOL_STR(rdev_set_badblocks) },
	{ 0xec80dffb, __VMLINUX_SYMBOL_STR(mem_map) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xd0ee38b8, __VMLINUX_SYMBOL_STR(schedule_timeout_uninterruptible) },
	{ 0xf12d798a, __VMLINUX_SYMBOL_STR(md_is_badblock) },
	{ 0xc7a1840e, __VMLINUX_SYMBOL_STR(llist_add_batch) },
	{ 0x43a53735, __VMLINUX_SYMBOL_STR(__alloc_workqueue_key) },
	{ 0xde3a09f9, __VMLINUX_SYMBOL_STR(bio_clone_mddev) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xf19e9355, __VMLINUX_SYMBOL_STR(cpu_online_mask) },
	{ 0xf309d07b, __VMLINUX_SYMBOL_STR(mddev_suspend) },
	{ 0x52212010, __VMLINUX_SYMBOL_STR(__tracepoint_block_bio_remap) },
	{ 0x36d57ffe, __VMLINUX_SYMBOL_STR(md_check_recovery) },
	{ 0x6b3e609d, __VMLINUX_SYMBOL_STR(__rt_mutex_init) },
	{ 0x1b2c012f, __VMLINUX_SYMBOL_STR(blk_queue_io_min) },
	{ 0xd3f57a2, __VMLINUX_SYMBOL_STR(_find_next_bit_le) },
	{ 0xc8d94dd1, __VMLINUX_SYMBOL_STR(md_write_end) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0xa1bd7822, __VMLINUX_SYMBOL_STR(__tracepoint_block_bio_complete) },
	{ 0xac1c6b4a, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0xacf7679, __VMLINUX_SYMBOL_STR(dma_issue_pending_all) },
	{ 0x6d921dae, __VMLINUX_SYMBOL_STR(bitmap_endwrite) },
	{ 0xd89a59ab, __VMLINUX_SYMBOL_STR(bitmap_unplug) },
	{ 0x50c89f23, __VMLINUX_SYMBOL_STR(__alloc_percpu) },
	{ 0x72580aa5, __VMLINUX_SYMBOL_STR(async_syndrome_val) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0xcc03202b, __VMLINUX_SYMBOL_STR(md_new_event) },
	{ 0x60ee9172, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x6dac7163, __VMLINUX_SYMBOL_STR(unregister_md_personality) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x90e9cc0a, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0xd697e69a, __VMLINUX_SYMBOL_STR(trace_hardirqs_on) },
	{ 0x583db796, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xc9ec4e21, __VMLINUX_SYMBOL_STR(free_percpu) },
	{ 0xb859f521, __VMLINUX_SYMBOL_STR(rt_spin_lock) },
	{ 0xe1cde6d6, __VMLINUX_SYMBOL_STR(atomic_dec_and_spin_lock) },
	{ 0x3c73e696, __VMLINUX_SYMBOL_STR(rt_spin_unlock) },
	{ 0xb3ce087d, __VMLINUX_SYMBOL_STR(bitmap_resize) },
	{ 0x9dfba532, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xfd2268fa, __VMLINUX_SYMBOL_STR(bio_reset) },
	{ 0xcb53d931, __VMLINUX_SYMBOL_STR(bitmap_start_sync) },
	{ 0xd27b25dd, __VMLINUX_SYMBOL_STR(blk_check_plugged) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x75a57170, __VMLINUX_SYMBOL_STR(md_register_thread) },
	{ 0xd6a9f72b, __VMLINUX_SYMBOL_STR(bio_init) },
	{ 0xf5e5a534, __VMLINUX_SYMBOL_STR(md_flush_request) },
	{ 0x706c5a65, __VMLINUX_SYMBOL_STR(preempt_count_sub) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x1f061b60, __VMLINUX_SYMBOL_STR(sysfs_create_group) },
	{ 0xc917e655, __VMLINUX_SYMBOL_STR(debug_smp_processor_id) },
	{ 0xbedbd2dc, __VMLINUX_SYMBOL_STR(md_do_sync) },
	{ 0x77745429, __VMLINUX_SYMBOL_STR(async_raid6_2data_recov) },
	{ 0x898edd63, __VMLINUX_SYMBOL_STR(async_trigger_callback) },
	{ 0xc8b78955, __VMLINUX_SYMBOL_STR(disk_stack_limits) },
	{ 0xead2d5eb, __VMLINUX_SYMBOL_STR(bitmap_close_sync) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x6c749afe, __VMLINUX_SYMBOL_STR(__tracepoint_block_unplug) },
	{ 0x95ac728c, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x8c03d20c, __VMLINUX_SYMBOL_STR(destroy_workqueue) },
	{ 0x465757c3, __VMLINUX_SYMBOL_STR(cpu_present_mask) },
	{ 0xbb45da7e, __VMLINUX_SYMBOL_STR(async_memcpy) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0x27d3782c, __VMLINUX_SYMBOL_STR(blk_recount_segments) },
	{ 0xc9445bd2, __VMLINUX_SYMBOL_STR(generic_make_request) },
	{ 0x6091797f, __VMLINUX_SYMBOL_STR(synchronize_rcu) },
	{ 0x43b0c9c3, __VMLINUX_SYMBOL_STR(preempt_schedule) },
	{ 0x49608959, __VMLINUX_SYMBOL_STR(migrate_disable) },
	{ 0x33ca785d, __VMLINUX_SYMBOL_STR(md_wait_for_blocked_rdev) },
	{ 0x42160169, __VMLINUX_SYMBOL_STR(flush_workqueue) },
	{ 0xbd2549a5, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0xffe6e047, __VMLINUX_SYMBOL_STR(bio_endio) },
	{ 0x3baf571, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0x59e5070d, __VMLINUX_SYMBOL_STR(__do_div64) },
	{ 0xc7944d35, __VMLINUX_SYMBOL_STR(__rt_spin_lock_init) },
	{ 0x3e2ca333, __VMLINUX_SYMBOL_STR(md_done_sync) },
	{ 0x682e871e, __VMLINUX_SYMBOL_STR(flush_signals) },
	{ 0xd93f4ade, __VMLINUX_SYMBOL_STR(sysfs_create_link) },
	{ 0xbd9074b1, __VMLINUX_SYMBOL_STR(blk_finish_plug) },
	{ 0x4b2b9720, __VMLINUX_SYMBOL_STR(async_xor_val) },
	{ 0x2430c857, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x2d2b004e, __VMLINUX_SYMBOL_STR(bitmap_cond_end_sync) },
	{ 0xd505e3fd, __VMLINUX_SYMBOL_STR(async_xor) },
	{ 0xddb1cd7, __VMLINUX_SYMBOL_STR(llist_reverse_order) },
	{ 0x776c353f, __VMLINUX_SYMBOL_STR(md_write_start) },
	{ 0xe915b500, __VMLINUX_SYMBOL_STR(bdevname) },
	{ 0x358dd1b2, __VMLINUX_SYMBOL_STR(__trace_note_message) },
	{ 0x5e2a1bea, __VMLINUX_SYMBOL_STR(async_tx_quiesce) },
	{ 0x5ffc64b6, __VMLINUX_SYMBOL_STR(rdev_clear_badblocks) },
	{ 0xd3e6f60d, __VMLINUX_SYMBOL_STR(cpu_possible_mask) },
	{ 0xd38f9b51, __VMLINUX_SYMBOL_STR(md_allow_write) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x72350130, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x3a1a1f4, __VMLINUX_SYMBOL_STR(md_set_array_sectors) },
	{ 0x996bdb64, __VMLINUX_SYMBOL_STR(_kstrtoul) },
	{ 0x4f14289e, __VMLINUX_SYMBOL_STR(sysfs_notify) },
	{ 0xd5440a40, __VMLINUX_SYMBOL_STR(md_wakeup_thread) },
	{ 0x9c863abf, __VMLINUX_SYMBOL_STR(kernfs_notify) },
	{ 0x1b056ec3, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x341dbfa3, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0xd0a54ee2, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x6e9ef562, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xfee09c47, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xcc2082f4, __VMLINUX_SYMBOL_STR(md_unregister_thread) },
	{ 0x5f2a5a9f, __VMLINUX_SYMBOL_STR(async_gen_syndrome) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xca3308b4, __VMLINUX_SYMBOL_STR(bitmap_startwrite) },
	{ 0x4990e632, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x327eea71, __VMLINUX_SYMBOL_STR(md_error) },
	{ 0xee6e693d, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0xa8ce6ea4, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0xd117b02a, __VMLINUX_SYMBOL_STR(mddev_resume) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0xf229424a, __VMLINUX_SYMBOL_STR(preempt_count_add) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0xec3d2e1b, __VMLINUX_SYMBOL_STR(trace_hardirqs_off) },
	{ 0x7d705738, __VMLINUX_SYMBOL_STR(blk_start_plug) },
	{ 0x97846689, __VMLINUX_SYMBOL_STR(blk_queue_max_write_same_sectors) },
	{ 0x4542e9ad, __VMLINUX_SYMBOL_STR(register_md_personality) },
	{ 0x9c3bc0ac, __VMLINUX_SYMBOL_STR(bitmap_end_sync) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=async_raid6_recov,md-mod,async_pq,async_tx,async_memcpy,async_xor";


MODULE_INFO(srcversion, "C65A341AA9A5305A0C8AE22");
